### PR TITLE
Maximum Upload Size configureable; meaningfull error message

### LINKED ISSUE #26: misbehave for sample-upload with files > 18Mb
if the file is larger than 18Mb, the master-gateway reads the username as empty and authentication fails

### PR DESCRIPTION
**Pull request by Ma-Shell**
There is a new configuration option for Master-Gateway, called "MaxUploadSize". If the sample size is bigger than the configured maximum, a 413-Error is returned, with an according error message.
This closes https://github.com/HolmesProcessing/Holmes-Gateway/issues/26

### CODE REVIEW

File: mastergateway/mastergateway.go [hunk 1]
```diff
@@ -31,6 +31,7 @@ type config struct {
 	OwnOrganization    string                           // The name of the own organization (Should also be present in the list "Organizations")
 	StorageURI         string                           // URI of HolmesStorage
 	AutoTasks          map[string](map[string][]string) // Tasks that should be automatically executed on new objects mimetype -> taskname -> args
+	MaxUploadSize      int64                            // The maximum size of a sample-upload in Megabyte
```
Comment (webstergd) [inline mastergateway/mastergateway.go]: might be better off with uint16 or uint32

Comment (Ma-Shell) [reply mastergateway/mastergateway.go]: Actually, you are right. I chose int64 because the bodie's content length is stored as an int64 and it wouldn't have let me compare these without typecasting

Comment (Ma-Shell) [reply mastergateway/mastergateway.go]: I changed it to uint32
